name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build main.pdf
      uses: dante-ev/latex-action@latest
      with:
        root_file: main.tex
