name: Publish

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set env
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "TODAY=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
    - name: Sed main.tex
      run: |
        sed -i 's/((date))/'"${{ env.TODAY }}"'/' main.tex
        sed -i 's/((version))/'"${{ env.RELEASE_VERSION }}"'/' main.tex
    - name: Build main.pdf
      uses: dante-ev/latex-action@latest
      with:
        root_file: main.tex
    - name: Rename main.pdf
      run: |
        mv main.pdf tmplcheatsheet-${{ env.RELEASE_VERSION }}.pdf
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: |
          tmplcheatsheet-${{ env.RELEASE_VERSION }}.pdf
